### ISSUE TITLE
Compile error installing 1.3.0

### ISSUE THREAD

**Issue by scarver2** [bolandrm/sassc-ruby#12]
Version 1.2.0 installed fine with Homebrew's libsass keg. However, version 1.3 is throwing an error.

Here is the log output from gem_make.out after `gem install sassc`:

```sh
/Users/me/.rvm/rubies/ruby-2.2.2/bin/ruby -rubygems /Users/me/.rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake RUBYARCHDIR=/Users/me/.rvm/gems/ruby-2.2.2/extensions/x86_64-darwin-14/2.2.0/sassc-1.3.0 RUBYLIBDIR=/Users/me/.rvm/gems/ruby-2.2.2/extensions/x86_64-darwin-14/2.2.0/sassc-1.3.0
git submodule update --init
fatal: Not a git repository (or any of the parent directories): .git
rake aborted!
Command failed with status (128): [git submodule update --init...]
/Users/me/.rvm/gems/ruby-2.2.2/gems/sassc-1.3.0/lib/tasks/libsass.rb:6:in `block (2 levels) in <top (required)>'
Tasks: TOP => default => libsass:compile => ext/libsass/lib/libsass.so => ext/libsass/.git
(See full trace by running task with --trace)

rake failed, exit code 1
```

Output from `brew info libsass`

```sh
libsass: stable 3.2.5 (bottled), HEAD
C implementation of a Sass compiler
https://github.com/sass/libsass
/usr/local/Cellar/libsass/3.2.4 (13 files, 4.6M)
  Poured from bottle
/usr/local/Cellar/libsass/3.2.5 (13 files, 4.6M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libsass.rb
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔
```

**Comment by bolandrm** [comment]
i think with the rake task set up the way it is, you need to be in the `sassc-1.3.0` gem directory when you call `rake`, in order to init the submodule.

at the moment, libsass which is installed elsewhere on your machine will be ignored-  the gem will always download the git repo and use that libsass version.

**Comment by scarver2** [comment]
I cleared out my gem repo inside of RVM.

git clone git@github.com:bolandrm/sassc-ruby.git
cd sassc-ruby
be rake libsass:compile
gem build sassc.gemspec
gem install ./sassc-1.3.0.gem

Still getting an installation error.

```sh
Building native extensions.  This could take a while...
ERROR:  Error installing ./sassc-1.3.0.gem:
	ERROR: Failed to build gem native extension.

    /Users/scarver2/.rvm/rubies/ruby-2.2.2/bin/ruby -rubygems /Users/scarver2/.rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake RUBYARCHDIR=/Users/scarver2/.rvm/gems/ruby-2.2.2/extensions/x86_64-darwin-14/2.2.0/sassc-1.3.0 RUBYLIBDIR=/Users/scarver2/.rvm/gems/ruby-2.2.2/extensions/x86_64-darwin-14/2.2.0/sassc-1.3.0
git submodule update --init
fatal: Not a git repository (or any of the parent directories): .git
rake aborted!
Command failed with status (128): [git submodule update --init...]
/Users/scarver2/.rvm/gems/ruby-2.2.2/gems/sassc-1.3.0/lib/tasks/libsass.rb:6:in `block (2 levels) in <top (required)>'
Tasks: TOP => default => libsass:compile => ext/libsass/lib/libsass.so => ext/libsass/.git
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/scarver2/.rvm/gems/ruby-2.2.2/gems/sassc-1.3.0 for inspection.
Results logged to /Users/scarver2/.rvm/gems/ruby-2.2.2/extensions/x86_64-darwin-14/2.2.0/sassc-1.3.0/gem_make.out
```

**Comment by bolandrm** [comment]
I'm having difficulty tracking this issue down.  It's likely due to https://github.com/bolandrm/sassc-ruby/commit/1f4c9b9d7773f0f63736f4e4b973321f5cbca2a5.  @edward any thoughts?

Prior to that commit, i'm actually not sure how the submodule was being initialized ...

**Comment by bolandrm** [comment]
Ah, perhaps we don't even need that submodule initialization in the Rakefile, because the files are being included in the gemspec?

**Comment by bolandrm** [comment]
@scarver2 after the build fails, are you able to go into `/Users/scarver2/.rvm/gems/ruby-2.2.2/gems/sassc-1.3.0` and check what is in there?  i.e. is the full libsass library in there?

**Comment by bolandrm** [comment]
@scarver2 I believe I've fixed this.  Please try out version 1.5.0 and let me know if you have any further problems.

**Comment by phillmv** [comment]
Hey!

I saw your post on reddit for sassc-rails and immediately got excited. Except, I'm also seeing this compilation error.

```bash
$ gem install sassc -v '1.5.0'
Building native extensions.  This could take a while...
ERROR:  Error installing sassc:
	ERROR: Failed to build gem native extension.

    /Users/phillmv/.rubies/ruby-2.2.0/bin/ruby -rubygems /Users/phillmv/.rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake RUBYARCHDIR=/Users/phillmv/.gem/ruby/2.2.0/extensions/x86_64-darwin-13/2.2.0-static/sassc-1.5.0 RUBYLIBDIR=/Users/phillmv/.gem/ruby/2.2.0/extensions/x86_64-darwin-13/2.2.0-static/sassc-1.5.0
git submodule update --init
fatal: Not a git repository (or any of the parent directories): .git
rake aborted!
Command failed with status (128): [git submodule update --init...]
/Users/phillmv/.gem/ruby/2.2.0/gems/sassc-1.5.0/lib/tasks/libsass.rb:6:in `block (2 levels) in <top (required)>'
Tasks: TOP => default => libsass:compile => ext/libsass/lib/libsass.so => ext/libsass/Makefile
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/phillmv/.gem/ruby/2.2.0/gems/sassc-1.5.0 for inspection.
Results logged to /Users/phillmv/.gem/ruby/2.2.0/extensions/x86_64-darwin-13/2.2.0-static/sassc-1.5.0/gem_make.out
```

fyi,
```bash
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
```

**Comment by phillmv** [comment]
Also worth noting that in `~/.gem/ruby/2.2.0/gems/sassc-1.5.0/ext/libsass`, I do seem to have the full libsass repo checked out.

**Comment by bolandrm** [comment]
@phillmv Thanks for the report!  I've released 1.5.1, can you please try installing that?


reproduced failed installation of 1.5.0:
```
🚀  sassc (master) →  gem install sassc -v '1.5.0'
Building native extensions.  This could take a while...
ERROR:  Error installing sassc:
	ERROR: Failed to build gem native extension.

    /Users/bolandrm/.rbenv/versions/2.1.4/bin/ruby -rubygems /Users/bolandrm/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/rake-10.1.0/bin/rake RUBYARCHDIR=/Users/bolandrm/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/sassc-1.5.0 RUBYLIBDIR=/Users/bolandrm/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/sassc-1.5.0
git submodule update --init
fatal: Not a git repository (or any of the parent directories): .git
rake aborted!
Command failed with status (128): [git submodule update --init...]

Tasks: TOP => default => libsass:compile => ext/libsass/lib/libsass.so => ext/libsass/Makefile
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/bolandrm/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sassc-1.5.0 for inspection.
Results logged to /Users/bolandrm/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/sassc-1.5.0/gem_make.out
```

Successful installation of 1.5.1
```
sassc (master) →  gem install sassc -v '1.5.1'
Fetching: sassc-1.5.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed sassc-1.5.1
1 gem installed
```

**Comment by phillmv** [comment]
```bash
$ gem install sassc -v '1.5.1'
Fetching: sassc-1.5.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed sassc-1.5.1
1 gem installed
```

Yay!

**Comment by scarver2** [comment]
Success! 1.5.1 installs and compiles without issue.

**Comment by edward** [comment]
> I'm having difficulty tracking this issue down. It's likely due to 1f4c9b9. @edward any thoughts?
> Prior to that commit, i'm actually not sure how the submodule was being initialized ...
>
> Ah, perhaps we don't even need that submodule initialization in the Rakefile, because the files are being included in the gemspec?

I remember spending a while trying to understand what Rubygems/the gemspec was doing. I believe you’re correct here.
